version = 0.1

[default.deploy.parameters]
stack_name = "ml-auth-lambda"
s3_prefix = "ml-auth-lambda"
s3_bucket = "mlholding-sam-deployments" 
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
# Cognito Parameters - REPLACE WITH ACTUAL VALUES
parameter_overrides = [
  "CognitoRegion=us-east-1",
  "CognitoPortalUserPoolId=REPLACE_WITH_ACTUAL_USER_POOL_ID",
  "CognitoPortalClientId=REPLACE_WITH_ACTUAL_CLIENT_ID"
]

[dev.deploy.parameters]
stack_name = "ml-auth-lambda-dev"
s3_prefix = "ml-auth-lambda-dev"
s3_bucket = "mlholding-sam-deployments" 
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = [
  "CognitoRegion=us-east-1",
  "CognitoPortalUserPoolId=REPLACE_WITH_DEV_USER_POOL_ID",
  "CognitoPortalClientId=REPLACE_WITH_DEV_CLIENT_ID"
]

[develop.deploy.parameters]
stack_name = "develop-ml-auth-lambda"
s3_prefix = "ml-auth-lambda/develop"
s3_bucket = "mlholding-sam-deployments" 
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
# Los parameter_overrides se pasan desde GitHub Actions usando secrets

[prod.deploy.parameters]
stack_name = "ml-auth-lambda-prod"
s3_prefix = "ml-auth-lambda-prod"
s3_bucket = "mlholding-sam-deployments"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = [
  "CognitoRegion=us-east-1",
  "CognitoPortalUserPoolId=REPLACE_WITH_PROD_USER_POOL_ID",
  "CognitoPortalClientId=REPLACE_WITH_PROD_CLIENT_ID"
]